import Head from "next/head";
import Intro_Section from "../components/Intro_Section";
import Slide from "../components/Slide";
import About from "../components/About";
import Contact from "../components/Contact";
import GetStarted from "../components/GetStarted";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro_Section />
      <Slide />
      <About />
      <Contact />
      <GetStarted />
    </div>
  );
}
